### PR TITLE
Removing support of process_p2m_lookup

### PR DESCRIPTION
**Pull request by iusyk**
Switch the branch of pvr_km_vgpu_img at the cleaned revision
"1.11/5375571-7.1.0-10.0.0_r3-xt0.2".

Signed-off-by: Ihor Usyk <ihor_usyk@epam.com>

### CODE REVIEW

**Comment by arminn** [comment]
Why android-10.0.0_r3-master-1 is used?

**Comment by iusyk** [comment]
> Why android-10.0.0_r3-master-1 is used?



> Why android-10.0.0_r3-master-1 is used?

Reason is to keep the changes in the separate branch, because there is a special branch in prod-devel for this manifest
Branch is renamed at android-10.0.0_r3-master-unsafe

**Comment by arminn** [comment]
It looks like 1.11/5375571-7.1.0-10.0.0_r3-xt0.2 should be used for android-10.0.0_r3-master
and 1.11/5375571-7.1.0-10.0.0_r3-xt0.1 should be used for android-10.0.0_r3-master-unsafe

**Comment by iusyk** [comment]
> It looks like 1.11/5375571-7.1.0-10.0.0_r3-xt0.2 should be used for android-10.0.0_r3-master
> and 1.11/5375571-7.1.0-10.0.0_r3-xt0.1 should be used for android-10.0.0_r3-master-unsafe

fixed
now prod-devel has unsafe branch with reference at unsafe branch of android_manifest

**Comment by arminn** [comment]
Now it is correct regarding branches, but patch description is not actual - plz update it like it is in PR

**Comment by otyshchenko1** [comment]
lgtm

**Review by arminn — CHANGES_REQUESTED** [review]
Patch description is not correct

**Comment by iusyk** [comment]
> Patch description is not correct

unnecessary sentence has been removed.

**Review by arminn — APPROVED** [review]

**Comment by arminn** [comment]
LGTM

**Pull request merged**
